url_shortener/models.py
import random, string, hashlib
from random import choices
from .extension import db
from datetime import datetime

class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512), unique=True)
    short_url = db.Column(db.String(8), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()

    
    def generate_short_link(self):
        #characters = string.digits + string.ascii_letters
        #short_url = ''.join(choices(characters, k=3))
        #num = random.randint(0, 10000)
        short_url = self.encode(self.original_url)

        link = self.query.filter_by(short_url=short_url).first()
        if link:
            return self.generate_short_link()

        return short_url

    def encode(self, longUrl):
        """ Encodes a URL to a shortened URL
        :type longUrl str
        :rtype: str
        """
        md5_hash = hashlib.md5(longUrl.encode('utf-8')).hexdigest()
        #md5_has has 32 bytes
        # get 3 slices of 10 bytes each and xor them so we end up with shorter URL suffix of len 8
        size = len(md5_hash)
        threeQ = int(size/3)

        x = md5_hash[:threeQ]
        y = md5_hash[threeQ:-threeQ]
        z = md5_hash[-threeQ:]

        xored = int(x, 16) ^ int(y, 16) ^ int(z, 16)

        return self.base62_encode(xored)

    def base62_encode(self, num):
        alphabet = string.digits + string.ascii_letters
        """Encode a positive number in Base X

        Arguments:
        - `num`: The number to encode
        """
        hash_str = []
        while num:
            num, r = divmod(num, len(alphabet))
            hash_str.append(alphabet[r])
        return ''.join(hash_str)

url_shortener/__init__.py
from flask import Flask
from .extension import db
from .routes import short

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)
    db.init_app(app)

    app.register_blueprint(short)
    return app

url_shortener/auth.py
from functools import wraps
from flask import request, Response, current_app

def check_auth(username, password):
    return username == current_app.config['ADMIN_USERNAME'] \
        and password == current_app.config['ADMIN_PASSWORD']

def authenticate():
    return Response('Could not verify your access level for that URL.\n'
    'You have to login with proper credentials', 401,
    {'WWW-Authenticate' : 'Basic realm="Login Required"'})

def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .models import Link
from .extension import db
from .auth import requires_auth

short = Blueprint('short', __name__)

@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()
    link.visits = link.visits + 1
    db.session.commit()
    return redirect(link.original_url)

@short.route('/')
def index():
    return render_template('index.html')

@short.route('/add_link', methods=['POST'])
def add_link():
    original_url = request.form['original_url']
    link = Link.query.filter_by(original_url=original_url).first()

    if(link):
        return render_template('link_added.html', 
        new_link=link.short_url, original_url=link.original_url)

    link = Link(original_url=original_url)
    db.session.add(link)
    db.session.commit()

    return render_template('link_added.html', 
        new_link=link.short_url, original_url=link.original_url)

@short.route('/stats')
@requires_auth
def stats():
    links = Link.query.all()
    return render_template('stats.html', links=links)

@short.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

url_shortener/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Short URL</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
    <section class="section">
        <div class="container">
            <form action="{{ url_for('short.add_link') }}" method="post" id="shortener">
                <label class="label">Original URL</label>
                <!-- <div class="field has-addons">
                    <div class="control">
                        <input class="input" type="text" name="original_url" placeholder="URL Input">
                    </div>
                    <div class="control">
                        <a class="button is-info" onclick="document.getElementById('shortener').submit();">
                            Shorten
                        </a>
                    </div>
                </div> -->

                <div class="field is-grouped">
                    <p class="control is-expanded">
                        <input class="input" type="text" name="original_url" placeholder="URL Input">
                    </p>
                    <p class="control">
                        <a class="button is-info" onclick="document.getElementById('shortener').submit();">
                            Shorten
                        </a>
                    </p>
                </div>
            </form>
        </div>
    </section>
</body>

</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Short URL</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
    <section class="section">
        <div class="container">
            <label class="label">Original URL</label>
            <div class="control">
                <input class="input" type="text" value="{{ original_url }}" readonly>
            </div>
            <br>
            <label class="label">Short URL</label>
            <div class="control">
                <input class="input" type="text"
                    value="{{ url_for('short.redirect_to_url', short_url=new_link, _external=True) }}" readonly>
            </div>
        </div>
    </section>
</body>

</html>

url_shortener/templates/stats.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Short URL - Stats</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
        <table class="table">
            <thead>
              <tr>
                <th>Original URL</th>
                <th>Short URL</th>
                <th>Visits</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Original URL</th>
                <th>Short URL</th>
                <th>Visits</th>
              </tr>
            </tfoot>
            <tbody>
                {% for link in links %}
                <tr>
                    <th>{{ link.original_url }}</th>
                    <td>{{ url_for('short.redirect_to_url', short_url=link.short_url, _external=True) }}</td>
                    <td>{{ link.visits }}</td>
                </tr>
                {% endfor %}   
            </tbody>
        </table>
    </div>
    </section>
</body>
</html>